### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by urdvr** [patarapolw/pyhandsontable#1]
Right now  pyhandsontable downloads and runs non-MIT code with the included comment

```
 * By installing, copying, or otherwise using this software, you agree to be bound by the terms
 * of its General Software License Terms ("Terms") outlined in a file "handsontable-pro-general-terms.pdf"
 * available in the main directory of the software repository.
 * This software is copyrighted and protected by copyright laws and international treaties.
 * 
 * You shall obtain a commercial license for this software at handsontable.com.
```
Could this be mentioned in the readme?

**Comment by patarapolw** [comment]
I will put this at the end of [`README.md`](https://github.com/patarapolw/pyhandsontable/blob/master/README.md#license). 

I don't know much about legality, but HandsOnTable Pro is quite troublesome. How should I license this work? Is MIT, OK. Also, do I have to use HandsOnTable, not Pro?

**Comment by urdvr** [comment]
I don't know if MIT is OK if you are interfacing with HandsOnTable Pro. My gut feeling is that it isn't, but I could be wrong.

Handsontable Community Edition seems to be MIT licensed, so that would be the safer option.

**Comment by patarapolw** [comment]
Should be corrected now.
